
notes = { "f#-1", "g", "g#", "a", "a#", "b", "c", "c#", "d", "d#", "e", "f", "f#-2" }
noteToIDMap = { {}, {}, {} }
for i=1,3 do
    proto = "octave-" .. i
    for n, note in ipairs(notes) do
        controllerID = rednet.lookup(proto, note)
        if (controllerID == nil)
        then
            print("No valid controller found for octave " .. i .. " and note " .. note)
            nonExistantFunctionCallToTerminateEarly()
        end
        noteToIDMap[i][note] = controllerID
    end
end

function pressNote(octave, note)
    updatePipe(true, octave, note)
end
function releaseNote(octave, note)
    updatePipe(false, octave, note)
end
function updatePipe(state, octave, note)
    rednet.send(noteToIDMap[octave][note], state, "octave-" .. octave)
end

sleep(2.4)
pressNote(1, "c")
pressNote(2, "g")
pressNote(2, "e")
sleep(0.525)
releaseNote(2, "e")
sleep(0.075)
pressNote(2, "e")
sleep(0.6)
releaseNote(2, "e")
pressNote(2, "f")
sleep(0.6)
releaseNote(2, "f")
pressNote(3, "g")
sleep(0.3)
releaseNote(2, "g")
sleep(0.225)
releaseNote(3, "g")
sleep(0.075)
pressNote(1, "b")
releaseNote(1, "c")
pressNote(2, "g")
pressNote(3, "g")
sleep(0.6)
pressNote(2, "f")
releaseNote(3, "g")
sleep(0.6)
pressNote(2, "e")
releaseNote(2, "f")
sleep(0.6)
pressNote(2, "d")
releaseNote(2, "e")
sleep(0.3)
releaseNote(2, "g")
sleep(0.3)
releaseNote(1, "b")
pressNote(1, "e")
pressNote(2, "g")
pressNote(2, "c")
releaseNote(2, "d")
sleep(0.525)
releaseNote(2, "c")
sleep(0.075)
pressNote(2, "c")
sleep(0.6)
pressNote(1, "d")
releaseNote(1, "e")
releaseNote(2, "g")
releaseNote(2, "c")
pressNote(2, "d")
sleep(0.6)
pressNote(1, "c")
releaseNote(1, "d")
releaseNote(2, "d")
pressNote(2, "e")
sleep(0.525)
releaseNote(2, "e")
sleep(0.075)
releaseNote(1, "c")
pressNote(2, "g")
pressNote(2, "e")
sleep(0.9)
pressNote(2, "d")
releaseNote(2, "e")
sleep(0.2625)
releaseNote(2, "d")
sleep(0.0375)
pressNote(2, "d")
sleep(0.9)
releaseNote(2, "g")
sleep(0.3)
pressNote(1, "c")
pressNote(2, "g")
releaseNote(2, "d")
pressNote(2, "e")
sleep(0.525)
releaseNote(2, "e")
sleep(0.075)
pressNote(2, "e")
sleep(0.6)
releaseNote(2, "e")
pressNote(2, "f")
sleep(0.6)
releaseNote(2, "f")
pressNote(3, "g")
sleep(0.3)
releaseNote(2, "g")
sleep(0.225)
releaseNote(3, "g")
sleep(0.075)
pressNote(1, "b")
releaseNote(1, "c")
pressNote(2, "g")
pressNote(3, "g")
sleep(0.6)
pressNote(2, "f")
releaseNote(3, "g")
sleep(0.6)
pressNote(2, "e")
releaseNote(2, "f")
sleep(0.6)
pressNote(2, "d")
releaseNote(2, "e")
sleep(0.3)
releaseNote(2, "g")
sleep(0.3)
releaseNote(1, "b")
pressNote(1, "e")
pressNote(2, "g")
pressNote(2, "c")
releaseNote(2, "d")
sleep(0.525)
releaseNote(2, "c")
sleep(0.075)
pressNote(2, "c")
sleep(0.6)
pressNote(1, "d")
releaseNote(1, "e")
releaseNote(2, "g")
releaseNote(2, "c")
pressNote(2, "d")
sleep(0.6)
pressNote(1, "c")
releaseNote(1, "d")
releaseNote(2, "d")
pressNote(2, "e")
sleep(0.6)
releaseNote(1, "c")
pressNote(1, "f")
pressNote(2, "g")
pressNote(2, "d")
releaseNote(2, "e")
sleep(0.7875)
releaseNote(2, "g")
sleep(0.1125)
pressNote(1, "e")
releaseNote(1, "f")
pressNote(2, "g")
pressNote(2, "c")
releaseNote(2, "d")
sleep(0.2625)
releaseNote(1, "e")
releaseNote(2, "g")
releaseNote(2, "c")
sleep(0.0375)
pressNote(1, "e")
pressNote(2, "g")
pressNote(2, "c")
sleep(1.05)
releaseNote(2, "g")
sleep(0.15)
pressNote(1, "b")
releaseNote(1, "e")
pressNote(2, "g")
releaseNote(2, "c")
pressNote(2, "d")
sleep(0.525)
releaseNote(2, "d")
sleep(0.075)
pressNote(2, "d")
sleep(0.45)
releaseNote(2, "g")
sleep(0.15)
releaseNote(1, "b")
pressNote(1, "c")
pressNote(2, "g")
releaseNote(2, "d")
pressNote(2, "e")
sleep(0.6)
pressNote(2, "c")
releaseNote(2, "e")
sleep(0.45)
releaseNote(2, "g")
sleep(0.15)
pressNote(1, "b")
releaseNote(1, "c")
pressNote(2, "g")
releaseNote(2, "c")
pressNote(2, "d")
sleep(0.6)
releaseNote(2, "d")
pressNote(2, "e")
sleep(0.3)
releaseNote(2, "e")
pressNote(2, "f")
sleep(0.15)
releaseNote(2, "g")
sleep(0.15)
releaseNote(1, "b")
pressNote(1, "c")
pressNote(2, "g")
pressNote(2, "e")
releaseNote(2, "f")
sleep(0.6)
pressNote(2, "c")
releaseNote(2, "e")
sleep(0.45)
releaseNote(2, "g")
sleep(0.15)
pressNote(1, "b")
releaseNote(1, "c")
pressNote(2, "g")
releaseNote(2, "c")
pressNote(2, "d")
sleep(0.6)
releaseNote(2, "d")
pressNote(2, "e")
sleep(0.3)
releaseNote(2, "e")
pressNote(2, "f")
sleep(0.3)
releaseNote(1, "b")
releaseNote(2, "g")
pressNote(2, "g#")
pressNote(2, "e")
releaseNote(2, "f")
sleep(0.6)
pressNote(2, "d")
releaseNote(2, "e")
sleep(0.6)
releaseNote(2, "g#")
pressNote(2, "a")
pressNote(2, "c")
releaseNote(2, "d")
sleep(0.6)
pressNote(2, "f#-1")
releaseNote(2, "a")
releaseNote(2, "c")
pressNote(2, "d")
sleep(0.6)
releaseNote(2, "f#-1")
pressNote(2, "g")
pressNote(2, "g")
releaseNote(2, "d")
sleep(0.6)
releaseNote(2, "g")
pressNote(2, "e")
sleep(0.45)
releaseNote(2, "g")
sleep(0.15)
pressNote(1, "c")
pressNote(2, "g")
sleep(0.45)
releaseNote(2, "e")
sleep(0.15)
pressNote(2, "e")
sleep(0.6)
releaseNote(2, "e")
pressNote(2, "f")
sleep(0.6)
releaseNote(2, "f")
pressNote(3, "g")
sleep(0.3)
releaseNote(2, "g")
sleep(0.225)
releaseNote(3, "g")
sleep(0.075)
pressNote(1, "b")
releaseNote(1, "c")
pressNote(2, "g")
pressNote(3, "g")
sleep(0.6)
pressNote(2, "f")
releaseNote(3, "g")
sleep(0.6)
pressNote(2, "e")
releaseNote(2, "f")
sleep(0.6)
pressNote(2, "d")
releaseNote(2, "e")
sleep(0.3)
releaseNote(2, "g")
sleep(0.3)
releaseNote(1, "b")
pressNote(1, "e")
pressNote(2, "g")
pressNote(2, "c")
releaseNote(2, "d")
sleep(0.525)
releaseNote(2, "c")
sleep(0.075)
pressNote(2, "c")
sleep(0.6)
pressNote(1, "d")
releaseNote(1, "e")
releaseNote(2, "g")
releaseNote(2, "c")
pressNote(2, "d")
sleep(0.6)
pressNote(1, "c")
releaseNote(1, "d")
releaseNote(2, "d")
pressNote(2, "e")
sleep(0.6)
releaseNote(1, "c")
pressNote(1, "f")
pressNote(2, "g")
pressNote(2, "d")
releaseNote(2, "e")
sleep(0.7875)
releaseNote(2, "g")
sleep(0.1125)
pressNote(1, "e")
releaseNote(1, "f")
pressNote(2, "g")
pressNote(2, "c")
releaseNote(2, "d")
sleep(0.2625)
releaseNote(1, "e")
releaseNote(2, "g")
releaseNote(2, "c")
sleep(0.0375)
pressNote(1, "e")
pressNote(2, "g")
pressNote(2, "c")
sleep(1.2)
releaseNote(1, "e")
releaseNote(2, "g")
releaseNote(2, "c")
