
notes = { "f#-1", "g", "g#", "a", "a#", "b", "c", "c#", "d", "d#", "e", "f", "f#-2" }
noteToIDMap = { {}, {}, {} }
visualizerID = rednet.lookup("visual", "visualizer")
if (visualizerID == nil)
then
    print("No valid controller found for visualizer")
    nonExistantFunctionCallToTerminateEarly()
end
for i=1,3 do
    proto = "octave-" .. i
    for n, note in ipairs(notes) do
        controllerID = rednet.lookup(proto, note)
        if (controllerID == nil)
        then
            print("No valid controller found for octave " .. i .. " and note " .. note)
            nonExistantFunctionCallToTerminateEarly()
        end
        noteToIDMap[i][note] = controllerID
    end
end

function pressNote(octave, note)
    updatePipe(true, octave, note)
end
function releaseNote(octave, note)
    updatePipe(false, octave, note)
end
function updatePipe(state, octave, note)
    rednet.send(noteToIDMap[octave][note], state, "octave-" .. octave)
    message = { note, octave, state }
    rednet.send(visualizerID, message, "visual")
end

pressNote(2, "a")
pressNote(2, "a")
sleep(0.3)
releaseNote(2, "a")
releaseNote(2, "a")
pressNote(2, "e")
pressNote(2, "e")
sleep(0.3)
releaseNote(2, "e")
releaseNote(2, "e")
pressNote(3, "c")
pressNote(3, "c")
sleep(0.3)
pressNote(2, "e")
pressNote(2, "e")
releaseNote(3, "c")
releaseNote(3, "c")
sleep(0.3)
pressNote(2, "a")
pressNote(2, "a")
releaseNote(2, "e")
releaseNote(2, "e")
sleep(0.3)
releaseNote(2, "a")
releaseNote(2, "a")
pressNote(2, "e")
pressNote(2, "e")
sleep(0.3)
releaseNote(2, "e")
releaseNote(2, "e")
pressNote(3, "c")
pressNote(3, "c")
sleep(0.3)
pressNote(2, "e")
pressNote(2, "e")
releaseNote(3, "c")
releaseNote(3, "c")
sleep(0.3)
pressNote(2, "a")
pressNote(2, "a")
releaseNote(2, "e")
releaseNote(2, "e")
sleep(0.3)
releaseNote(2, "a")
releaseNote(2, "a")
pressNote(2, "e")
pressNote(2, "e")
sleep(0.3)
releaseNote(2, "e")
releaseNote(2, "e")
pressNote(3, "c")
pressNote(3, "c")
sleep(0.3)
pressNote(2, "e")
pressNote(2, "e")
releaseNote(3, "c")
releaseNote(3, "c")
sleep(0.3)
pressNote(2, "a")
pressNote(2, "a")
releaseNote(2, "e")
releaseNote(2, "e")
sleep(0.3)
releaseNote(2, "a")
releaseNote(2, "a")
pressNote(2, "e")
pressNote(2, "e")
sleep(0.3)
releaseNote(2, "e")
releaseNote(2, "e")
pressNote(3, "c")
pressNote(3, "c")
sleep(0.3)
pressNote(2, "e")
pressNote(2, "e")
releaseNote(3, "c")
releaseNote(3, "c")
sleep(0.3)
pressNote(2, "a")
pressNote(2, "a")
releaseNote(2, "e")
releaseNote(2, "e")
sleep(0.3)
releaseNote(2, "a")
releaseNote(2, "a")
pressNote(2, "e")
pressNote(2, "e")
sleep(0.3)
releaseNote(2, "e")
releaseNote(2, "e")
pressNote(3, "c")
pressNote(3, "c")
sleep(0.3)
pressNote(2, "e")
pressNote(2, "e")
releaseNote(3, "c")
releaseNote(3, "c")
sleep(0.3)
pressNote(2, "a")
pressNote(2, "a")
releaseNote(2, "e")
releaseNote(2, "e")
sleep(0.3)
releaseNote(2, "a")
releaseNote(2, "a")
pressNote(2, "e")
pressNote(2, "e")
sleep(0.3)
releaseNote(2, "e")
releaseNote(2, "e")
pressNote(3, "c")
pressNote(3, "c")
sleep(0.3)
pressNote(2, "e")
pressNote(2, "e")
releaseNote(3, "c")
releaseNote(3, "c")
sleep(0.3)
pressNote(2, "a")
pressNote(2, "a")
releaseNote(2, "e")
releaseNote(2, "e")
sleep(0.3)
releaseNote(2, "a")
releaseNote(2, "a")
pressNote(2, "e")
pressNote(2, "e")
sleep(0.3)
releaseNote(2, "e")
releaseNote(2, "e")
pressNote(3, "c")
pressNote(3, "c")
sleep(0.3)
pressNote(2, "e")
pressNote(2, "e")
releaseNote(3, "c")
releaseNote(3, "c")
sleep(0.3)
pressNote(2, "a")
pressNote(2, "a")
releaseNote(2, "e")
releaseNote(2, "e")
sleep(0.3)
releaseNote(2, "a")
releaseNote(2, "a")
pressNote(2, "e")
pressNote(2, "e")
sleep(0.3)
releaseNote(2, "e")
releaseNote(2, "e")
pressNote(3, "c")
pressNote(3, "c")
sleep(0.3)
pressNote(2, "e")
pressNote(2, "e")
releaseNote(3, "c")
releaseNote(3, "c")
sleep(0.3)
pressNote(2, "a")
pressNote(2, "a")
releaseNote(2, "e")
releaseNote(2, "e")
sleep(0.3)
releaseNote(2, "a")
releaseNote(2, "a")
pressNote(2, "e")
pressNote(2, "e")
sleep(0.3)
releaseNote(2, "e")
releaseNote(2, "e")
pressNote(3, "c")
pressNote(3, "c")
sleep(0.3)
pressNote(2, "e")
pressNote(2, "e")
releaseNote(3, "c")
releaseNote(3, "c")
sleep(0.3)
pressNote(2, "a")
pressNote(2, "a")
releaseNote(2, "e")
releaseNote(2, "e")
sleep(0.3)
releaseNote(2, "a")
releaseNote(2, "a")
pressNote(2, "e")
pressNote(2, "e")
sleep(0.3)
releaseNote(2, "e")
releaseNote(2, "e")
pressNote(3, "c")
pressNote(3, "c")
sleep(0.3)
pressNote(2, "e")
pressNote(2, "e")
releaseNote(3, "c")
releaseNote(3, "c")
sleep(0.3)
pressNote(2, "a")
pressNote(2, "a")
releaseNote(2, "e")
releaseNote(2, "e")
sleep(0.3)
releaseNote(2, "a")
releaseNote(2, "a")
pressNote(2, "d#")
pressNote(2, "d#")
sleep(0.3)
releaseNote(2, "d#")
releaseNote(2, "d#")
pressNote(3, "b")
pressNote(3, "b")
sleep(0.3)
pressNote(2, "d#")
pressNote(2, "d#")
releaseNote(3, "b")
releaseNote(3, "b")
sleep(0.3)
pressNote(2, "a")
pressNote(2, "a")
releaseNote(2, "d#")
releaseNote(2, "d#")
sleep(0.3)
releaseNote(2, "a")
releaseNote(2, "a")
pressNote(2, "d#")
pressNote(2, "d#")
sleep(0.3)
releaseNote(2, "d#")
releaseNote(2, "d#")
pressNote(3, "b")
pressNote(3, "b")
sleep(0.3)
pressNote(2, "d#")
pressNote(2, "d#")
releaseNote(3, "b")
releaseNote(3, "b")
sleep(0.3)
pressNote(2, "a")
pressNote(2, "a")
releaseNote(2, "d#")
releaseNote(2, "d#")
sleep(0.3)
releaseNote(2, "a")
releaseNote(2, "a")
pressNote(2, "d")
pressNote(2, "d")
sleep(0.3)
releaseNote(2, "d")
releaseNote(2, "d")
pressNote(3, "b")
pressNote(3, "b")
sleep(0.3)
pressNote(2, "d")
pressNote(2, "d")
releaseNote(3, "b")
releaseNote(3, "b")
sleep(0.3)
pressNote(2, "a")
pressNote(2, "a")
releaseNote(2, "d")
releaseNote(2, "d")
sleep(0.3)
releaseNote(2, "a")
releaseNote(2, "a")
pressNote(2, "d")
pressNote(2, "d")
sleep(0.3)
releaseNote(2, "d")
releaseNote(2, "d")
pressNote(3, "b")
pressNote(3, "b")
sleep(0.3)
pressNote(2, "d")
pressNote(2, "d")
releaseNote(3, "b")
releaseNote(3, "b")
sleep(0.3)
pressNote(2, "a")
pressNote(2, "a")
releaseNote(2, "d")
releaseNote(2, "d")
sleep(0.3)
releaseNote(2, "a")
releaseNote(2, "a")
pressNote(2, "c")
pressNote(2, "c")
sleep(0.3)
releaseNote(2, "c")
releaseNote(2, "c")
pressNote(3, "a")
pressNote(3, "a")
sleep(0.3)
pressNote(2, "c")
pressNote(2, "c")
releaseNote(3, "a")
releaseNote(3, "a")
sleep(0.3)
pressNote(2, "b")
pressNote(2, "b")
releaseNote(2, "c")
releaseNote(2, "c")
sleep(0.3)
releaseNote(2, "b")
releaseNote(2, "b")
pressNote(2, "d")
pressNote(2, "d")
sleep(0.3)
releaseNote(2, "d")
releaseNote(2, "d")
pressNote(3, "g#")
pressNote(3, "g#")
sleep(0.3)
pressNote(2, "d")
pressNote(2, "d")
releaseNote(3, "g#")
releaseNote(3, "g#")
sleep(0.3)
pressNote(2, "a")
pressNote(2, "a")
releaseNote(2, "d")
releaseNote(2, "d")
sleep(0.3)
releaseNote(2, "a")
releaseNote(2, "a")
pressNote(2, "e")
pressNote(2, "e")
sleep(0.3)
releaseNote(2, "e")
releaseNote(2, "e")
pressNote(3, "c")
pressNote(3, "c")
sleep(0.3)
pressNote(2, "e")
pressNote(2, "e")
releaseNote(3, "c")
releaseNote(3, "c")
sleep(0.3)
pressNote(2, "a")
pressNote(2, "a")
releaseNote(2, "e")
releaseNote(2, "e")
sleep(0.3)
releaseNote(2, "a")
releaseNote(2, "a")
pressNote(2, "e")
pressNote(2, "e")
sleep(0.3)
releaseNote(2, "e")
releaseNote(2, "e")
pressNote(3, "c")
pressNote(3, "c")
sleep(0.3)
pressNote(2, "e")
pressNote(2, "e")
releaseNote(3, "c")
releaseNote(3, "c")
sleep(0.3)
pressNote(2, "a")
pressNote(2, "a")
releaseNote(2, "e")
releaseNote(2, "e")
sleep(0.3)
releaseNote(2, "a")
releaseNote(2, "a")
pressNote(2, "d#")
pressNote(2, "d#")
sleep(0.3)
releaseNote(2, "d#")
releaseNote(2, "d#")
pressNote(3, "b")
pressNote(3, "b")
sleep(0.3)
pressNote(2, "d#")
pressNote(2, "d#")
releaseNote(3, "b")
releaseNote(3, "b")
sleep(0.3)
pressNote(2, "a")
pressNote(2, "a")
releaseNote(2, "d#")
releaseNote(2, "d#")
sleep(0.3)
releaseNote(2, "a")
releaseNote(2, "a")
pressNote(2, "d#")
pressNote(2, "d#")
sleep(0.3)
releaseNote(2, "d#")
releaseNote(2, "d#")
pressNote(3, "b")
pressNote(3, "b")
sleep(0.3)
pressNote(2, "d#")
pressNote(2, "d#")
releaseNote(3, "b")
releaseNote(3, "b")
sleep(0.3)
pressNote(2, "a")
pressNote(2, "a")
releaseNote(2, "d#")
releaseNote(2, "d#")
sleep(0.3)
releaseNote(2, "a")
releaseNote(2, "a")
pressNote(2, "d")
pressNote(2, "d")
sleep(0.3)
releaseNote(2, "d")
releaseNote(2, "d")
pressNote(3, "b")
pressNote(3, "b")
sleep(0.3)
pressNote(2, "d")
pressNote(2, "d")
releaseNote(3, "b")
releaseNote(3, "b")
sleep(0.3)
pressNote(2, "a")
pressNote(2, "a")
releaseNote(2, "d")
releaseNote(2, "d")
sleep(0.3)
releaseNote(2, "a")
releaseNote(2, "a")
pressNote(2, "d")
pressNote(2, "d")
sleep(0.3)
releaseNote(2, "d")
releaseNote(2, "d")
pressNote(3, "b")
pressNote(3, "b")
sleep(0.3)
pressNote(2, "d")
pressNote(2, "d")
releaseNote(3, "b")
releaseNote(3, "b")
sleep(0.3)
releaseNote(2, "d")
releaseNote(2, "d")
pressNote(3, "g#")
pressNote(3, "g#")
pressNote(3, "e")
pressNote(3, "e")
sleep(0.3)
pressNote(3, "f")
pressNote(3, "f")
releaseNote(3, "g#")
releaseNote(3, "g#")
pressNote(3, "d")
pressNote(3, "d")
releaseNote(3, "e")
releaseNote(3, "e")
sleep(0.3)
pressNote(3, "e")
pressNote(3, "e")
releaseNote(3, "f")
releaseNote(3, "f")
pressNote(3, "c")
pressNote(3, "c")
releaseNote(3, "d")
releaseNote(3, "d")
sleep(0.3)
pressNote(3, "d")
pressNote(3, "d")
releaseNote(3, "e")
releaseNote(3, "e")
pressNote(3, "b")
pressNote(3, "b")
releaseNote(3, "c")
releaseNote(3, "c")
sleep(0.3)
pressNote(2, "a")
pressNote(2, "a")
pressNote(3, "c")
pressNote(3, "c")
releaseNote(3, "d")
releaseNote(3, "d")
pressNote(3, "a")
pressNote(3, "a")
releaseNote(3, "b")
releaseNote(3, "b")
sleep(0.3)
releaseNote(2, "a")
releaseNote(2, "a")
pressNote(2, "e")
pressNote(2, "e")
releaseNote(3, "c")
releaseNote(3, "c")
releaseNote(3, "a")
releaseNote(3, "a")
sleep(0.3)
releaseNote(2, "e")
releaseNote(2, "e")
pressNote(3, "c")
pressNote(3, "c")
sleep(0.3)
pressNote(2, "e")
pressNote(2, "e")
releaseNote(3, "c")
releaseNote(3, "c")
sleep(0.3)
pressNote(2, "a")
pressNote(2, "a")
releaseNote(2, "e")
releaseNote(2, "e")
sleep(0.3)
releaseNote(2, "a")
releaseNote(2, "a")
pressNote(2, "e")
pressNote(2, "e")
sleep(0.3)
releaseNote(2, "e")
releaseNote(2, "e")
pressNote(3, "c")
pressNote(3, "c")
sleep(0.3)
pressNote(2, "e")
pressNote(2, "e")
releaseNote(3, "c")
releaseNote(3, "c")
sleep(0.3)
pressNote(2, "a")
pressNote(2, "a")
releaseNote(2, "e")
releaseNote(2, "e")
sleep(0.3)
releaseNote(2, "a")
releaseNote(2, "a")
pressNote(2, "e")
pressNote(2, "e")
sleep(0.3)
releaseNote(2, "e")
releaseNote(2, "e")
pressNote(3, "c")
pressNote(3, "c")
sleep(0.3)
pressNote(2, "e")
pressNote(2, "e")
releaseNote(3, "c")
releaseNote(3, "c")
sleep(0.2571428571428555)
releaseNote(2, "e")
sleep(0.042857142857144474)
pressNote(2, "a")
pressNote(2, "a")
releaseNote(2, "e")
pressNote(2, "e")
sleep(0.0375)
pressNote(2, "e")
sleep(0.0375)
pressNote(3, "c")
sleep(0.0375)
pressNote(3, "c")
sleep(0.48749999999999993)
releaseNote(2, "a")
releaseNote(2, "a")
releaseNote(2, "e")
sleep(0.0375)
releaseNote(2, "e")
sleep(0.0375)
releaseNote(3, "c")
sleep(0.0375)
releaseNote(3, "c")
sleep(0.18749999999999997)
pressNote(2, "g#")
pressNote(2, "g#")
pressNote(3, "g#")
pressNote(3, "g#")
sleep(0.3)
releaseNote(2, "g#")
releaseNote(2, "g#")
pressNote(2, "a")
pressNote(2, "a")
releaseNote(3, "g#")
releaseNote(3, "g#")
pressNote(3, "a")
pressNote(3, "a")
sleep(0.3)
releaseNote(2, "a")
releaseNote(2, "a")
pressNote(2, "b")
pressNote(2, "b")
releaseNote(3, "a")
releaseNote(3, "a")
pressNote(3, "b")
pressNote(3, "b")
sleep(0.3)
releaseNote(2, "b")
releaseNote(2, "b")
pressNote(2, "c")
pressNote(2, "c")
releaseNote(3, "b")
releaseNote(3, "b")
pressNote(3, "c")
pressNote(3, "c")
sleep(0.3)
releaseNote(2, "c")
releaseNote(2, "c")
pressNote(2, "d")
pressNote(2, "d")
releaseNote(3, "c")
releaseNote(3, "c")
pressNote(3, "d")
pressNote(3, "d")
sleep(0.3)
releaseNote(2, "d")
releaseNote(2, "d")
pressNote(2, "e")
pressNote(2, "e")
releaseNote(3, "d")
releaseNote(3, "d")
pressNote(3, "e")
pressNote(3, "e")
sleep(0.3)
releaseNote(2, "e")
releaseNote(2, "e")
releaseNote(3, "e")
releaseNote(3, "e")
sleep(0.3)
pressNote(3, "a")
pressNote(3, "a")
pressNote(3, "a")
pressNote(3, "a")
sleep(0.3)
releaseNote(3, "a")
releaseNote(3, "a")
releaseNote(3, "a")
releaseNote(3, "a")
sleep(0.22499999999999998)
pressNote(3, "c")
pressNote(3, "c")
pressNote(3, "d#")
sleep(0.0375)
pressNote(3, "d#")
sleep(0.0375)
pressNote(3, "a")
pressNote(3, "a")
sleep(1.2)
pressNote(3, "b")
pressNote(3, "b")
releaseNote(3, "c")
releaseNote(3, "c")
releaseNote(3, "d#")
pressNote(3, "e")
pressNote(3, "e")
pressNote(3, "g#")
pressNote(3, "g#")
releaseNote(3, "a")
releaseNote(3, "a")
sleep(0.0375)
releaseNote(3, "d#")
sleep(0.5625)
releaseNote(3, "b")
releaseNote(3, "b")
releaseNote(3, "e")
releaseNote(3, "e")
releaseNote(3, "g#")
releaseNote(3, "g#")
pressNote(3, "a")
pressNote(3, "a")
pressNote(3, "d#")
pressNote(3, "d#")
sleep(0.3)
releaseNote(3, "a")
releaseNote(3, "a")
pressNote(3, "a#")
pressNote(3, "a#")
releaseNote(3, "d#")
releaseNote(3, "d#")
pressNote(3, "e")
pressNote(3, "e")
sleep(0.3)
pressNote(3, "a")
pressNote(3, "a")
releaseNote(3, "a#")
releaseNote(3, "a#")
pressNote(3, "d#")
pressNote(3, "d#")
releaseNote(3, "e")
releaseNote(3, "e")
sleep(0.6)
pressNote(3, "g#")
pressNote(3, "g#")
releaseNote(3, "a")
releaseNote(3, "a")
pressNote(3, "d")
pressNote(3, "d")
releaseNote(3, "d#")
releaseNote(3, "d#")
sleep(0.6)
releaseNote(3, "g#")
releaseNote(3, "g#")
releaseNote(3, "d")
releaseNote(3, "d")
sleep(0.6)
pressNote(3, "c#")
pressNote(3, "c#")
pressNote(3, "g")
pressNote(3, "g")
pressNote(3, "c#")
pressNote(3, "c#")
sleep(0.3)
releaseNote(3, "c#")
releaseNote(3, "c#")
pressNote(3, "d")
pressNote(3, "d")
releaseNote(3, "g")
releaseNote(3, "g")
pressNote(3, "g#")
pressNote(3, "g#")
releaseNote(3, "c#")
releaseNote(3, "c#")
pressNote(3, "d")
pressNote(3, "d")
sleep(0.3)
pressNote(3, "c#")
pressNote(3, "c#")
releaseNote(3, "d")
releaseNote(3, "d")
pressNote(3, "g")
pressNote(3, "g")
releaseNote(3, "g#")
releaseNote(3, "g#")
pressNote(3, "c#")
pressNote(3, "c#")
releaseNote(3, "d")
releaseNote(3, "d")
sleep(0.6)
pressNote(3, "c")
pressNote(3, "c")
releaseNote(3, "c#")
releaseNote(3, "c#")
pressNote(3, "f#-2")
pressNote(3, "f#-2")
releaseNote(3, "g")
releaseNote(3, "g")
pressNote(3, "c")
pressNote(3, "c")
releaseNote(3, "c#")
releaseNote(3, "c#")
sleep(0.6)
releaseNote(3, "c")
releaseNote(3, "c")
releaseNote(3, "f#-2")
releaseNote(3, "f#-2")
releaseNote(3, "c")
releaseNote(3, "c")
sleep(0.6)
pressNote(3, "b")
pressNote(3, "b")
pressNote(3, "f")
pressNote(3, "f")
pressNote(3, "b")
pressNote(3, "b")
sleep(0.3)
releaseNote(3, "b")
releaseNote(3, "b")
pressNote(3, "c")
pressNote(3, "c")
releaseNote(3, "f")
releaseNote(3, "f")
pressNote(3, "f#-2")
pressNote(3, "f#-2")
releaseNote(3, "b")
releaseNote(3, "b")
pressNote(3, "c")
pressNote(3, "c")
sleep(0.3)
pressNote(3, "b")
pressNote(3, "b")
releaseNote(3, "c")
releaseNote(3, "c")
pressNote(3, "f")
pressNote(3, "f")
releaseNote(3, "f#-2")
releaseNote(3, "f#-2")
pressNote(3, "b")
pressNote(3, "b")
releaseNote(3, "c")
releaseNote(3, "c")
sleep(1.2)
pressNote(3, "a#")
pressNote(3, "a#")
releaseNote(3, "b")
releaseNote(3, "b")
pressNote(3, "e")
pressNote(3, "e")
releaseNote(3, "f")
releaseNote(3, "f")
pressNote(3, "a#")
pressNote(3, "a#")
releaseNote(3, "b")
releaseNote(3, "b")
sleep(0.6)
releaseNote(3, "a#")
releaseNote(3, "a#")
releaseNote(3, "e")
releaseNote(3, "e")
releaseNote(3, "a#")
releaseNote(3, "a#")
sleep(0.3)
pressNote(2, "d#")
pressNote(2, "d#")
pressNote(3, "a#")
pressNote(3, "a#")
pressNote(3, "d#")
pressNote(3, "d#")
sleep(0.3)
releaseNote(2, "d#")
releaseNote(2, "d#")
pressNote(2, "e")
pressNote(2, "e")
releaseNote(3, "a#")
releaseNote(3, "a#")
pressNote(3, "b")
pressNote(3, "b")
releaseNote(3, "d#")
releaseNote(3, "d#")
pressNote(3, "e")
pressNote(3, "e")
sleep(0.2571428571428555)
releaseNote(3, "b")
sleep(0.042857142857144474)
pressNote(2, "b")
pressNote(2, "b")
releaseNote(2, "e")
releaseNote(2, "e")
pressNote(3, "g#")
pressNote(3, "g#")
releaseNote(3, "b")
pressNote(3, "b")
pressNote(3, "b")
releaseNote(3, "e")
releaseNote(3, "e")
sleep(0.3)
pressNote(2, "a#")
pressNote(2, "a#")
releaseNote(2, "b")
releaseNote(2, "b")
pressNote(3, "g")
pressNote(3, "g")
releaseNote(3, "g#")
releaseNote(3, "g#")
pressNote(3, "a#")
pressNote(3, "a#")
releaseNote(3, "b")
releaseNote(3, "b")
sleep(0.3)
releaseNote(2, "a#")
releaseNote(2, "a#")
pressNote(2, "b")
pressNote(2, "b")
releaseNote(3, "g")
releaseNote(3, "g")
pressNote(3, "g#")
pressNote(3, "g#")
releaseNote(3, "a#")
releaseNote(3, "a#")
pressNote(3, "b")
pressNote(3, "b")
sleep(0.2571428571428555)
releaseNote(2, "b")
sleep(0.042857142857144474)
pressNote(2, "g#")
pressNote(2, "g#")
releaseNote(2, "b")
pressNote(2, "b")
pressNote(2, "b")
pressNote(2, "e")
pressNote(2, "e")
releaseNote(3, "g#")
releaseNote(3, "g#")
releaseNote(3, "b")
releaseNote(3, "b")
sleep(0.6)
releaseNote(2, "g#")
releaseNote(2, "g#")
releaseNote(2, "b")
releaseNote(2, "b")
releaseNote(2, "e")
releaseNote(2, "e")
sleep(0.6)
pressNote(2, "g#")
pressNote(2, "g#")
pressNote(2, "b")
pressNote(2, "b")
pressNote(2, "e")
pressNote(2, "e")
sleep(0.6)
releaseNote(2, "g#")
releaseNote(2, "g#")
releaseNote(2, "b")
releaseNote(2, "b")
releaseNote(2, "e")
releaseNote(2, "e")
sleep(0.6)
pressNote(2, "g#")
pressNote(2, "g#")
sleep(0.056249999999999994)
pressNote(2, "b")
sleep(0.01875)
pressNote(2, "b")
sleep(0.075)
pressNote(2, "e")
pressNote(2, "e")
sleep(1.03125)
releaseNote(2, "b")
sleep(0.01875)
releaseNote(2, "g#")
releaseNote(2, "g#")
releaseNote(2, "b")
releaseNote(2, "e")
releaseNote(2, "e")
